### PR TITLE
Second part of fix for Amazon Linux

### LINKED ISSUE #110: package_name could not be resolved with new Amazon Linux 2017.03
### Cookbook version
0.4.5

### Chef-client version
all

### Platform Details
Amazon Linux 2017.03

### Scenario:
Install HTTPD

### Steps to Reproduce:
Install HTTPD

### Expected Result:
HTTPD installed

### Actual Result:
Error Message: You must supply a name when declaring a package resource

package_name has no standard value and for AmazonLinux 2017.03 no package name could be found in the local map.
-> Cookbook failing

### PR DESCRIPTION
**Pull request by et304383**
### Description

Fixes for Amazon Linux 2017.03

### Issues Resolved

#110 

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by eric-tucker** [comment]
As a side note, this is all reminiscent of the MySQL cookbook issues that went on for YEARS with regards to Amazon Linux version handling.  A better solution is needed.

**Comment by AntoineBro** [comment]
👍  
would be great to be able to merge this one.

**Comment by someara** [comment]
re: https://github.com/chef/chef/issues/4103

**Comment by tas50** [comment]
Merging under the obvious fix policy

**Pull request merged**
