### PR TITLE
Added package name to httpd_module LWRP

### PR DESCRIPTION
**Pull request by ikari7789**
Added package name to httpd_module LWRP otherwise install fails if you use non-system default name. Changed version to httpd_version to match LWRP resource.

### CODE REVIEW

**Comment by eeyun** [comment]
Hey @ikari7789 would you be able to provide an example to repro the issue you're trying to solve here?  A little more info would be rad!

**Comment by ikari7789** [comment]
If you want to change the httpd package name, it becomes irrelevant due to the fact that when installing the httpd package it then installs some base modules, but since those don't define the package name it attempts to use the default package name.
Beyond that, the version is unspecified so you also cannot specify anything except the default.

**Comment by ikari7789** [comment]
Also, "version" is incorrect for http_module. It should be "http_version."

**Comment by iennae** [comment]
Thanks for your contribution @ikari7789! I've rebased and added this in with PR #77. I'm going to go ahead and close this pull request.

**Pull request closed without merging**
