### PR TITLE
bunch of cleanup

### PR DESCRIPTION
**Pull request by lamont-granquist**
- remove the useless httpd_service abstract base class (because this is ruby, not java)
- fix stubbing the service helpers in Chef so that ChefSpec is happy
- flatten the class hierarchy
- default DSL names based on class names are less likely to be confusing now that the base classes are gone

### CODE REVIEW

**Comment by lamont-granquist** [comment]
This now passes ChefSpec, but fails on TK for some reason.

**Comment by someara** [comment]
This isn't working... it's skipping all the common resources (package and friends) and jumping straight to the service resources

https://gist.github.com/someara/c9b4db2300dd2600e085#file-gistfile1-txt-L70

**Comment by someara** [comment]
The current implementation subclasses Chef::Provider::HttpdService::Rhel, then adds :start :stop, :reload and friends.

https://github.com/chef-cookbooks/httpd/blob/ea6270af99e67d1228e6f3efd5ef1fa7a3c47075/libraries/provider_httpd_service_rhel_sysvinit.rb#L8

Also, I seem to remember using "action :create" from the LWRP DSL vs 'def action_create' affecting the behavior of use_inline_resources and notifications somehow. I can't remember the specifics.

-s

**Comment by lamont-granquist** [comment]
action :create just calls define_method to create an `#action_create` method.  there's no difference in terms of function.  but i can't use the `action` helper in a module because it comes from LWRPBase and can't have a module include/subclass a class (AFAIK).

i'll have to look at the breakage on monday

**Comment by lamont-granquist** [comment]
And instead of subclassing Chef::Provider::HttpdService::Rhel we mixin Chef::Provider::HttpdServiceRhel which accomplishes the same thing, but using the mixin is more appropriate for simple code sharing than using inheritance/subclassing, and at the same time we avoid turning that abstract class into a provider.

I'm pretty sure its the right direction for how it should be designed, but I just ran out of gas debugging it on Friday.

**Comment by lamont-granquist** [comment]
@someara i think this is ready now

**Comment by lamont-granquist** [comment]
passes rubocop, test kitchen, chefspec, travis is broken

**Comment by tpetchel** [comment]
@lamont-granquist @someara I get this error from both Test Kitchen and a live node running CentOS 6.5. Can anyone see anything wrong with what I'm doing?

https://gist.github.com/tpetchel/77b001b52ce60299a315

**Comment by tpetchel** [comment]
@lamont-granquist @someara the error was mine. In my .conf file, I specified `/var/log/apache2` instead of `/var/log/httpd`. The error manifested in the service restart.

Upside is that I can confirm that these changes work on CentOS 6.5, both from test kitchen and a live EC2 instance. :+1: 

Thanks for helping offline.

**Pull request merged**
