### PR TITLE
add tests for httpd_service actions

### LINKED ISSUE #117: httpd_service actions :create and :delete do not de/provision systemd units
### Cookbook version
0.4.5

### Chef-client version
13.3.42

### Platform Details
platforms:
  - name: ubuntu-16.04
  - name: centos-7.3

### Scenario:
We are unable to start the httpd service after configuring the httpd_service resource using "action :create" because httpd_service only defines the systemd unit in the :start action.

### Steps to Reproduce:
1. `chef generate cookbook httpd-bug`
2. add `depends 'httpd'` to metadata.rb
3. add the following three lines to recipes/default.rb
```
apt_update 'update'
httpd_service('proxy') { action :create }
service('httpd-proxy') { action :start }
```
4. `kitchen converge`

### Expected Result:
The httpd_service resource with only action :create should install and configure (but not start) all of the components of the Apache httpd service being defined.

### Actual Result:
The httpd_service resource installs and configures the Apache httpd application, but does not define the httpd-proxy service.

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '5'
           ---- Begin output of /bin/systemctl --system start httpd-proxy ----
           STDOUT: 
           STDERR: Failed to start httpd-proxy.service: Unit not found.
           ---- End output of /bin/systemctl --system start httpd-proxy ----
           Ran /bin/systemctl --system start httpd-proxy returned 5

### PR DESCRIPTION
**Pull request by karmix**
Signed-off-by: Doug Knight <doug.knight@karmix.org>

### Description

Update documentation to include missing `httpd_service` actions and add integration tests to verify that each `httpd_service` action is working properly.  Marks the test related to issue #117 is pending, as well as two more tests that identified previously undiscovered bugs related to the `:delete` action.

### Issues Resolved

Resolves #117

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [X] New functionality includes testing.
- [X] New functionality has been documented in the README if applicable
- [X] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by tas50** [comment]
Hey @karmix there's a large number of inspec failures for those new tests.

**Comment by karmix** [comment]
Sorry, I had accidentally pushed some incomplete code to that branch.
I rebased the first commit and fixed a few tests that were not properly updated after some copy/paste operations.  It looks like the three failing suites are the same opensuse-leap ones that are still failing on master.  They all pass in test kitchen if I make `http_binary_name` in `helpers_rhel.rb` always return 'httpd'.

**Comment by karmix** [comment]
The second commit is ready to go.  It enables one of the pending tests and overhauls the `:delete` action for the `httpd_service` resource so that the test passes.

`httpd_service_rhel.rb` and `httpd_service_debian.rb` handled the cleanup of `/etc/#{apache_name}` differently.  `httpd_service_rhel.rb` removed the directory recursively, while `httpd_service_debian.rb` removed most of the files under that directory but did not remove the directory at all (leaving stuff behind and causing the test to fail.  This change refactors both `:delete` actions by:

1. removing the `/etc/#{apache_name}` directory recursively in `httpd_service_debian.rb`
2. eliminating resources that delete files located under a directory that is already being removed recursively.
3. DRYing up the existing code.

Alternatively, we could remove only the files generated by the `:create` action, and only remove the directories if when they are empty.  This would ensure that the `:delete` action did not remove any user generated files.  However, it would also be more work to maintain, require a user to `:delete` each `httpd_module` and `httpd_config` resource, separately, and be inconsistent with other design choices regarding externally generated files (such as the removal of logs during the `:delete` action).

**Comment by karmix** [comment]
The third commit is working fine, now that the second is fixed.  All that's left is a final commit to enable the service deletion test and update that code.  I don't believe it will take very long to write.  I expect to push it to this branch sometime tomorrow.

**Comment by tas50** [comment]
This is a beautiful PR. Thanks for taking the time to handle DRYing up things as well. That was definitely needed.

**Comment by karmix** [comment]
All of the tests are now enabled, and code updated so they pass.  If this looks like the direction the project should go, everything is ready to go.  These patches do change behavior (e.g. the service is now deleted by the `:delete` action, service creation moved to `:create`), the maintainers will need to decide whether this is a bug-fix or feature change, and whether it is appropriate for minor revision.

**Comment by tas50** [comment]
I think this is a feature change, but I'm ok with that. I'm really interested in how someone that utilizes this cookbook works around some of the pitfalls and how people would like to move forward with refactoring things so that this cookbook can become more useful.

**Pull request merged**
